project: miq
global:
  domain: 127.0.0.1.nip.io
components:
  db:
    type: database
    image: postgres:15-alpine
  redis:
    type: cache
    image: redis:7-alpine
  backend:
    type: worker
    image: ghcr.io/quentinchirol/miq:latest
  frontend:
    type: web
    image: ghcr.io/quentinchirol/miq:latest
    public: true
    port: 80
