apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quentinchirol/Yush-kubernetes.git
    targetRevision: HEAD
    path: apps/Portfolio
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true