apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2 # On veut 2 pods Nginx
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: nginx
        image: ghcr.io/quentinchirol/portfolio:sha-3368bb8
        ports:
        - containerPort: 80

