apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
spec:
  type: NodePort
  ports:
  - port: 90
    targetPort: 90
    nodePort: 30090
    protocol: TCP
  selector:
    app: nginx
