apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # On utilise LoadBalancer pour l'exposer sur le port 80 de ton hôte Windows
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx
