project: portfolio
global:
  domain: 127.0.0.1.nip.io
  repoUrl: https://github.com/quentinchirol/Portfolio.git
components:
  portfolio:
    type: web
    image: ghcr.io/quentinchirol/portfolio-portfolio:latest
    public: true
    dockerfile: Dockerfile
